# bumping this file (testing)
sudo: required

language: node_js

services:
  - docker

before_install:
  - docker-compose build unit-tests

script:
  - docker-compose run --rm unit-tests
  - docker-compose run --rm unit-tests ./node_modules/eslint/bin/eslint.js .
