version: "2"
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/code
      - /code/node_modules
    depends_on:
      - db
    links:
      - db
    environment:
      - MONGO_DATABASE_URL=mongodb://db:27017/majicbox
    ports:
      - "8000:8000"
  db:
    image: mongo
    restart: always
    volumes:
      - /db-volume-mongo
    ports:
      - "27017:27017"
