version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
    depends_on:
      - mongo
    links:
      - "mongo:database"
    ports:
      - "8000:8000"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
