version: "2"
services:
  web:
    extends:
      file: docker-common.yml
      service: web
    volumes:
      - ./:/app
    depends_on:
      - db
    links:
      - db
    environment:
      - MONGO_DATABASE_URL=mongodb://db:27017/majicbox
  db:
    image: mongo
    volumes:
      - "./mongo-data:/data/db"
    ports:
      - "27017:27017"
